routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth','validate_user'])->group(function () {
    Route::get('/', function () {

        if (auth()->user()->id_type_user == 2){
            $empresas = DB::table('medico_empresa')->join('empresa','empresa.id','=','medico_empresa.id_empresa')
                ->where('id_medico',auth()->user()->id)->where('medico_empresa.logica_delete',1)->select('empresa.*')->get();
            return view('welcome',compact('empresas'));
        }else{
            $empresas = null;
            return view('welcome',compact('empresas'));
        }

    })->name('inicio');
    Route::resources([
        'user' => 'UserController',
        'empresa' => 'EmpresaController',
        'puesto' => 'PuestoController',
        'area' => 'AreaController',
        'rugro' => 'RugroController',
    ]);
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/import-users', 'ImportController@user')->name('import.user');
    Route::get('/empresa/asignar/{id_empresa}', 'EmpresaController@asignar')->name('empresa.asignar');
    Route::post('/empresa/asignar-guardar', 'EmpresaController@asignar_guardar')->name('empresa.asignar_guardar');
    Route::get('/empresa/asignar-delete/{id_medico}/{id_empresa}', 'EmpresaController@asignar_delete')->name('empresa.asignar_delete');
    Route::get('/user-colaboradores','UserController@user_colaboradores')->name('user.colaboradores');
    Route::get('/empresa-perfil','EmpresaController@empresa_perfil')->name('empresa.perfil');

    Route::get('colaboradores-list/{id_empresa}','EmpresaController@list_empresa')->name('list-empresa');
    Route::get('diagnosticar/{id_fase}','EmpresaController@diagnosticar')->name('diagnosticar');

    Route::post('diagnosticar-save','EmpresaController@diagnosticar_save')->name('diagnosticar.save');
    Route::get('diagnosticar-edit/{id_diagnostico}','EmpresaController@diagnosticar_edit')->name('diagnostico.edit');
    Route::post('diagnosticar-update','EmpresaController@diagnosticar_update')->name('diagnostico.update');
    Route::get('diagnosticar-delete/{id_diagnostico}','EmpresaController@diagnosticar_delete')->name('diagnostico.delete');
    Route::post('save-reporte','UserController@saveReporte')->name('save-reporte');

    Route::get('calificar-activo/{id_usuario}','UserController@calificarActivo')->name('calificar-activo');
    Route::get('calificar-sano/{id_usuario}','UserController@calificarSano')->name('calificar-sano');
    Route::get('calificar-sospechoso/{id_usuario}','UserController@calificarSospechoso')->name('calificar-sospechoso');

    Route::get('reportes/{type}/{fecha1}/{fecha2}/{id_empresa?}','ReporeteController@reportes')->name('reportes');
    Route::get('export/{type}/{fecha1}/{fecha2}','ReporeteController@export')->name('export');
    // paginas de medico
    // - descanso medico
    Route::get('descanso-medico','MedicoController@descansoMedico')->name('descanso-medico');
    Route::post('descanso-medico-edad','MedicoController@descansoMedicoEdad')->name('descanso-medico-edad');
    Route::post('descanso-medico-save','MedicoController@descansoMedicoSave')->name('descanso-medico.save');
    Route::get('descanso-medico-pdf/{id_hdm}','MedicoController@descansoMedicoPdf')->name('descanso-medico-pdf');

    // - reincorporación laboral
    Route::get('reincorporacion-laboral','MedicoController@reincorporacionLaboral')->name('reincorporacion-laboral');
    Route::post('reincorporacion-laboral-edad','MedicoController@reincorporacionLaboralEdad')->name('reincorporacion-laboral.edad');
    Route::post('reincorporacion-laboral-save','MedicoController@reincorporacionLaboralSave')->name('reincorporacion-laboral.save');
    Route::get('reincorporacion-laboral-pdf/{id_hdm}','MedicoController@reincorporacionLaboralPdf')->name('reincorporacion-laboral-pdf');

    Route::get('map-calor','MapController@MapController')->name('mapa.calor');
    
    Route::get('bitacora-medico','BitacoraController@bitacoraMedico')->name('bitacora-medico');
    Route::post('bitacora-medico-save','BitacoraController@saveBitacoraMedico')->name('bitacora-medico-save');
    Route::post('bitacora-medico-consult','BitacoraController@bitacoraMedicoConsult')->name('bitacora-medico-consult');

});

Route::middleware(['auth'])->group(function () {
    Route::resource('form-colaborador','ColaboraadorController');
    Route::get('perfil','ColaboraadorController@perfil')->name('form-colaborador.perfil');
    Route::put('perfil-update/{id}','ColaboraadorController@perfilUpdate')->name('form-colaborador.perfil.update');
    Route::get('/seguimiento/{id_user}','UserController@seguimiento')->name('seguimiento');
});

Auth::routes();

app/Models/Cargo.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Cargo
 * 
 * @property int $id
 * @property int $id_empresa
 * @property string $titulo
 * @property int $logica_delete
 * @property Carbon $created_at
 * @property Carbon $updated_at
 *
 * @package App\Models
 */
class Cargo extends Model
{
	protected $table = 'cargo';

	protected $casts = [
		'id_empresa' => 'int',
		'logica_delete' => 'int'
	];

	protected $fillable = [
		'id_empresa',
		'titulo',
		'logica_delete'
	];
}

app/Models/User.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class User
 * 
 * @property int $id
 * @property int $id_type_user
 * @property string $name
 * @property string $last_name
 * @property string $email
 * @property Carbon $email_verified_at
 * @property string $password
 * @property string $type_documento
 * @property string $documento
 * @property string $celular
 * @property string $direccion
 * @property string $foto
 * @property string $dias
 * @property string $estado_salud
 * @property string $seguimiento
 * @property string $cumplimiento
 * @property int $id_departamento
 * @property int $id_provincia
 * @property int $id_distrito
 * @property int $logica_delete
 * @property string $remember_token
 * @property Carbon $created_at
 * @property Carbon $updated_at
 *
 * @package App\Models
 */
class User extends Model
{
	protected $table = 'users';

	protected $casts = [
		'id_type_user' => 'int',
		'id_departamento' => 'int',
		'id_provincia' => 'int',
		'id_distrito' => 'int',
		'logica_delete' => 'int'
	];

	protected $dates = [
		'email_verified_at'
	];

	protected $hidden = [
		'password',
		'remember_token'
	];

	protected $fillable = [
		'id_type_user',
		'name',
		'last_name',
		'email',
		'email_verified_at',
		'password',
		'type_documento',
		'documento',
		'celular',
		'direccion',
		'foto',
		'dias',
		'estado_salud',
		'seguimiento',
		'cumplimiento',
		'id_departamento',
		'id_provincia',
		'id_distrito',
		'logica_delete',
		'remember_token'
	];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'documento'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CargoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cargo;
use App\Models\Empresa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CargoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $empresas = Empresa::where('logica_delete',1)->get();
        $cargos = DB::table('cargo')->join('empresa','empresa.id','=','cargo.id_empresa')->
        where('cargo.logica_delete',1)->select('cargo.*','empresa.title as empresa')->get();
        return view('admin.users.cargo.index',compact('empresas','cargos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if ($request->input('type_id') == 1){
            $rules = [
                'empresa' => 'required',
                'titulo' => 'required'
            ];

            $messages = [
                'empresa.required' => 'El campo empresa es campo obligatorio',
                'titulo.required' => 'El campo titulo es campo obligatorio',
            ];

            $this->validate($request, $rules, $messages);

            $cargo = new Cargo();
            $cargo->id_empresa = $request->input('empresa');
            $cargo->titulo = $request->input('titulo');

            if ($cargo->save()){
                return redirect()->route('cargo.index')->with('success','El cargo se guardo correctamente');
            }else{
                return redirect()->route('cargo.index')->with('error','Ups, error al guardar la información, intente mas tarde');
            }

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $cargo_consult = Cargo::where('id',$id)->first();
        $empresas = Empresa::where('logica_delete',1)->get();
        $cargos = DB::table('cargo')->join('empresa','empresa.id','=','cargo.id_empresa')->
        where('cargo.logica_delete',1)->select('cargo.*','empresa.title as empresa')->get();
        return view('admin.users.cargo.edit',compact('empresas','cargos','cargo_consult','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        if ($request->input('type_id') == 1){
            $rules = [
                'empresa' => 'required',
                'titulo' => 'required'
            ];

            $messages = [
                'empresa.required' => 'El campo empresa es campo obligatorio',
                'titulo.required' => 'El campo titulo es campo obligatorio',
            ];

            $this->validate($request, $rules, $messages);

            $update = DB::table('cargo')->where('id',$id)->update([
                    'id_empresa' => $request->input('empresa'),
                    'titulo' => $request->input('titulo')
                ]);

            if ($update){
                return redirect()->route('cargo.edit',$id)->with('success','Se ha actualizado correctamente');
            }else{
                return redirect()->route('cargo.edit',$id)->with('error','Ups, error al guardar la información, intente mas tarde');
            }

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $delete = DB::table('cargo')->where('id',$id)->update([
            'logica_delete' => 0
        ]);

        if ($delete){
            return response()->json(['success'=>true,'message'=>'se ha eliminado correctamente']);
        }else{
            return response()->json(['success'=>false,'message'=>'Error al momento de eliminar el cargo, intente mas tarde']);
        }
    }
}

resources/views/admin/users/cargo/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">

                <div class="row mb-4">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Cargos</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('user.index')}}">Usuarios</a></li>
                            <li class="breadcrumb-item active">Cargos</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif


                @if (session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif

                @if(auth()->user()->id_type_user == 1)
                    <div class="row" id="form-user-dash">
                        <section class="col-lg-12 connectedSortable ui-sortable">
                            <div class="card">
                                <div class="card-header ui-sortable-handle">
                                    <h3 class="card-title">Formulario de cargos</h3>
                                </div>
                                <div class="card-body">
                                    <form action="{{route('cargo.update',$id)}}" method="POST">
                                        @csrf
                                        @method('put')
                                        <input type="hidden" name="type_id" value="{{auth()->user()->id_type_user}}">
                                        <div class="row">
                                            <div class="form-group col-md-6">
                                                <label for="">Empresa</label>
                                                <select name="empresa" id="" class="form-control">
                                                    @foreach($empresas as $empresa)
                                                        @if($cargo_consult->id_empresa == $empresa->id)
                                                            <option value="{{$empresa->id}}" selected>{{$empresa->title}}</option>
                                                        @else
                                                            <option value="{{$empresa->id}}">{{$empresa->title}}</option>
                                                        @endif
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="">Titulo</label>
                                                <input type="text" name="titulo" class="form-control" value="{{$cargo_consult->titulo}}">
                                            </div>
                                            <div class="form-group col-md-12 text-right mb-0">
                                                <button class="btn btn-primary" type="submit">Guardar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </section>
                    </div>
                @endif

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Lista de cargos</h3>
                    </div>
                    <div class="card-body">
                        <table class="table" id="example2">
                            <thead>
                            <th>Nº</th>
                            <th>Titulo</th>
                            <th>Empresa</th>
                            <th>Opciones</th>
                            </thead>
                            <tbody>
                            @php $c = 1 @endphp
                            @foreach($cargos as $cargo)
                                <tr>
                                    <td>{{$c++}}</td>
                                    <td>{{$cargo->titulo}}</td>
                                    <td>{{$cargo->empresa}}</td>
                                    <td>
                                        <a href="{{route('cargo.edit',$cargo->id)}}" class="btn btn-success"><i class="fas fa-pen"></i></a>
                                        <button onclick="deleteCargo({{$cargo->id}},'{{$cargo->titulo}}')" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>

            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
    </div>
@endsection

@section('script')
    <script>
        $("#example2").DataTable({
            "responsive": true,
            "autoWidth": false,
        });

        function deleteCargo(id,name) {
            swal({
                title: `¿ Estas seguro que quieres eliminar a ${name} ?`,
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajaxSetup({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            }
                        });

                        $.ajax({
                            url: '../../cargo/'+id,
                            type: 'delete',
                            dataType: "JSON",
                            data: {
                                "id": id
                            },
                            success: function (response)
                            {
                                if(response.success){
                                    swal(response.message, {
                                        icon: "success",
                                    });
                                    setTimeout(function () {
                                        location.reload();
                                    },1000)
                                }
                            },
                        })


                    }
                });
        }
    </script>
@endsection

resources/views/admin/users/cargo/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">

                <div class="row mb-4">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Cargos</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('user.index')}}">Usuarios</a></li>
                            <li class="breadcrumb-item active">Cargos</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif


                @if (session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif

                @if(auth()->user()->id_type_user == 1)
                    <div class="row" id="form-user-dash">
                        <section class="col-lg-12 connectedSortable ui-sortable">
                            <div class="card">
                                <div class="card-header ui-sortable-handle">
                                    <h3 class="card-title">Formulario de cargos</h3>
                                </div>
                                <div class="card-body">
                                    <form action="{{route('cargo.store')}}" method="POST">
                                        @csrf
                                        <input type="hidden" name="type_id" value="{{auth()->user()->id_type_user}}">
                                        <div class="row">
                                            <div class="form-group col-md-6">
                                                <label for="">Empresa</label>
                                                <select name="empresa" id="" class="form-control">
                                                    <option value="" selected disabled>Elegir una empresa</option>
                                                    @foreach($empresas as $empresa)
                                                        <option value="{{$empresa->id}}">{{$empresa->title}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="">Titulo</label>
                                                <input type="text" name="titulo" class="form-control">
                                            </div>
                                            <div class="form-group col-md-12 text-right mb-0">
                                                <button class="btn btn-primary" type="submit">Guardar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </section>
                    </div>
                @endif

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Lista de cargos</h3>
                    </div>
                    <div class="card-body">
                        <table class="table" id="example2">
                            <thead>
                                <th>Nº</th>
                                <th>Titulo</th>
                                <th>Empresa</th>
                                <th>Opciones</th>
                            </thead>
                            <tbody>
                                @php $c = 1 @endphp
                                @foreach($cargos as $cargo)
                                    <tr>
                                        <td>{{$c++}}</td>
                                        <td>{{$cargo->titulo}}</td>
                                        <td>{{$cargo->empresa}}</td>
                                        <td>
                                            <a href="{{route('cargo.edit',$cargo->id)}}" class="btn btn-success"><i class="fas fa-pen"></i></a>
                                            <button onclick="deleteCargo({{$cargo->id}},'{{$cargo->titulo}}')" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>

            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
    </div>
@endsection

@section('script')
    <script>
        $("#example2").DataTable({
            "responsive": true,
            "autoWidth": false,
        });

        function deleteCargo(id,name) {
            swal({
                title: `¿ Estas seguro que quieres eliminar a ${name} ?`,
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajaxSetup({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            }
                        });

                        $.ajax({
                            url: '../../cargo/'+id,
                            type: 'delete',
                            dataType: "JSON",
                            data: {
                                "id": id
                            },
                            success: function (response)
                            {
                                if(response.success){
                                    swal(response.message, {
                                        icon: "success",
                                    });
                                    setTimeout(function () {
                                        location.reload();
                                    },1000)
                                }
                            },
                        })


                    }
                });
        }
    </script>
@endsection