routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth','validate_user'])->group(function () {
    Route::get('/', function () {

        if (auth()->user()->id_type_user == 2){
            $empresas = DB::table('medico_empresa')->join('empresa','empresa.id','=','medico_empresa.id_empresa')
                ->where('id_medico',auth()->user()->id)->where('medico_empresa.logica_delete',1)->select('empresa.*')->get();
            return view('welcome',compact('empresas'));
        }else{
            $empresas = null;
            return view('welcome',compact('empresas'));
        }

    })->name('inicio');
    Route::resources([
        'user' => 'UserController',
        'empresa' => 'EmpresaController',
        'puesto' => 'PuestoController',
        'area' => 'AreaController',
        'rugro' => 'RugroController',
    ]);
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/import-users', 'ImportController@user')->name('import.user');
    Route::get('/empresa/asignar/{id_empresa}', 'EmpresaController@asignar')->name('empresa.asignar');
    Route::post('/empresa/asignar-guardar', 'EmpresaController@asignar_guardar')->name('empresa.asignar_guardar');
    Route::get('/empresa/asignar-delete/{id_medico}/{id_empresa}', 'EmpresaController@asignar_delete')->name('empresa.asignar_delete');
    Route::get('/user-colaboradores','UserController@user_colaboradores')->name('user.colaboradores');
    Route::get('/empresa-perfil','EmpresaController@empresa_perfil')->name('empresa.perfil');

    Route::get('colaboradores-list/{id_empresa}','EmpresaController@list_empresa')->name('list-empresa');
    Route::get('diagnosticar/{id_fase}','EmpresaController@diagnosticar')->name('diagnosticar');

    Route::post('diagnosticar-save','EmpresaController@diagnosticar_save')->name('diagnosticar.save');
    Route::get('diagnosticar-edit/{id_diagnostico}','EmpresaController@diagnosticar_edit')->name('diagnostico.edit');
    Route::post('diagnosticar-update','EmpresaController@diagnosticar_update')->name('diagnostico.update');
    Route::get('diagnosticar-delete/{id_diagnostico}','EmpresaController@diagnosticar_delete')->name('diagnostico.delete');
    Route::post('save-reporte','UserController@saveReporte')->name('save-reporte');

    Route::get('calificar-activo/{id_usuario}','UserController@calificarActivo')->name('calificar-activo');
    Route::get('calificar-sano/{id_usuario}','UserController@calificarSano')->name('calificar-sano');
    Route::get('calificar-sospechoso/{id_usuario}','UserController@calificarSospechoso')->name('calificar-sospechoso');

    Route::get('reportes/{type}/{fecha1}/{fecha2}/{id_empresa?}','ReporeteController@reportes')->name('reportes');
    Route::get('export/{type}/{fecha1}/{fecha2}','ReporeteController@export')->name('export');
    // paginas de medico
    // - descanso medico
    Route::get('descanso-medico','MedicoController@descansoMedico')->name('descanso-medico');
    Route::post('descanso-medico-edad','MedicoController@descansoMedicoEdad')->name('descanso-medico-edad');
    Route::post('descanso-medico-save','MedicoController@descansoMedicoSave')->name('descanso-medico.save');
    Route::get('descanso-medico-pdf/{id_hdm}','MedicoController@descansoMedicoPdf')->name('descanso-medico-pdf');

    // - reincorporación laboral
    Route::get('reincorporacion-laboral','MedicoController@reincorporacionLaboral')->name('reincorporacion-laboral');
    Route::post('reincorporacion-laboral-edad','MedicoController@reincorporacionLaboralEdad')->name('reincorporacion-laboral.edad');
    Route::post('reincorporacion-laboral-save','MedicoController@reincorporacionLaboralSave')->name('reincorporacion-laboral.save');
    Route::get('reincorporacion-laboral-pdf/{id_hdm}','MedicoController@reincorporacionLaboralPdf')->name('reincorporacion-laboral-pdf');

    Route::get('map-calor','MapController@MapController')->name('mapa.calor');
    
    Route::get('bitacora-medico','BitacoraController@bitacoraMedico')->name('bitacora-medico');
    Route::post('bitacora-medico-save','BitacoraController@saveBitacoraMedico')->name('bitacora-medico-save');
    Route::post('bitacora-medico-consult','BitacoraController@bitacoraMedicoConsult')->name('bitacora-medico-consult');

});

Route::middleware(['auth'])->group(function () {
    Route::resource('form-colaborador','ColaboraadorController');
    Route::get('perfil','ColaboraadorController@perfil')->name('form-colaborador.perfil');
    Route::put('perfil-update/{id}','ColaboraadorController@perfilUpdate')->name('form-colaborador.perfil.update');
    Route::get('/seguimiento/{id_user}','UserController@seguimiento')->name('seguimiento');
});

Auth::routes();

app/Models/Empresa.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Empresa
 * 
 * @property int $id
 * @property string $title
 * @property string $ruc
 * @property string $direccion
 * @property string $telefono
 * @property string $correo
 * @property int $id_rugro
 * @property int $logica_delete
 * @property Carbon $created_at
 * @property Carbon $updated_at
 *
 * @package App\Models
 */
class Empresa extends Model
{
	protected $table = 'empresa';

	protected $casts = [
		'id_rugro' => 'int',
		'logica_delete' => 'int'
	];

	protected $fillable = [
		'title',
		'ruc',
		'direccion',
		'telefono',
		'correo',
		'id_rugro',
		'logica_delete'
	];
}

app/Http/Controllers/EmpresaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Area;
use App\Models\Diagnostico;
use App\Models\Empresa;
use App\Models\MedicoEmpresa;
use App\Models\Puesto;
use App\Models\Rugro;
use App\Models\TypeUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EmpresaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $rugros_count = Rugro::where('logica_delete',1)->count();

        if ($rugros_count == 0){
            return redirect()->route('rugro.index')->with('error','No se encontro rugros ingresados, comience registrando un rugro para crear una empresa');
        }else{
            $empresas = DB::table('empresa')->join('rugro','rugro.id','=','empresa.id_rugro')->
            where('empresa.logica_delete',1)->select('empresa.*','rugro.titulo as rugro')->get();
            $rugros = Rugro::where('logica_delete',1)->get();
            $medicos = DB::table('users')->where('id_type_user',2)->get();
            return view('admin.empresa.index',compact('empresas','rugros','medicos'));
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         $rules = [
             'nombre' => 'required',
             'ruc' => 'required',
             'direccion' => 'required',
             'telefono' => 'required',
             'correo' => 'required',
             'rugro' => 'required',
         ];

        $messages = [
            'nombre.required' => 'El campo nombre es campo obligatorio',
            'ruc.required' => 'El campo ruc es campo obligatorio',
            'telefono.required' => 'El telefono titulo es campo obligatorio',
            'correo.required' => 'El campo correo es campo obligatorio',
            'rugro.required' => 'El campo correo es campo obligatorio',
            'direccion.required' => 'El campo dirección es campo obligatorio',
        ];

        $this->validate($request, $rules, $messages);

        $empresa = new Empresa();
        $empresa->title = $request->input('nombre');
        $empresa->ruc = $request->input('ruc');
        $empresa->direccion = $request->input('direccion');
        $empresa->telefono = $request->input('telefono');
        $empresa->correo = $request->input('correo');
        $empresa->id_rugro = $request->input('rugro');

        if ($empresa->save()){
            return redirect()->route('empresa.index')->with('success', 'La empresa ha sido guardad con exito');
        }else{
            return redirect()->route('empresa.index')->with('error', 'Ha ocurrido un error, intente mas tarde');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $usuarios = DB::table('users')->
        join('type_user','type_user.id','=','users.id_type_user')->
        join('datos_colaborador','datos_colaborador.id_user','=','users.id')->
        where('users.logica_delete',1)->where('datos_colaborador.id_empresa',$id)->
        select('users.*','type_user.title')->get();
        return view('admin.empresa.show',compact('usuarios','id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $rugros = Rugro::where('logica_delete',1)->get();
        $empresas = Empresa::where('logica_delete',1)->get();
        $dato = Empresa::where('id',$id)->first();
        return view('admin.empresa.edit',compact('empresas','dato','id','rugros'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $rules = [
            'nombre' => 'required',
            'ruc' => 'required',
            'direccion' => 'required',
            'telefono' => 'required',
            'correo' => 'required',
            'rugro' => 'required',
        ];

        $messages = [
            'nombre.required' => 'El campo nombre es campo obligatorio',
            'ruc.required' => 'El campo ruc es campo obligatorio',
            'telefono.required' => 'El telefono titulo es campo obligatorio',
            'correo.required' => 'El campo correo es campo obligatorio',
            'rugro.required' => 'El campo correo es campo obligatorio',
            'direccion.required' => 'El campo dirección es campo obligatorio',
        ];

        $this->validate($request, $rules, $messages);

        $empresa = new Empresa();
        $empresa->title = $request->input('nombre');
        $empresa->ruc = $request->input('ruc');
        $empresa->direccion = $request->input('direccion');
        $empresa->telefono = $request->input('telefono');

        $update = DB::table('empresa')->where('id',$id)->update([
            'title' => $request->input('nombre'),
            'ruc' => $request->input('ruc'),
            'direccion' => $request->input('direccion'),
            'telefono' => $request->input('telefono')
        ]);

        if ($update){
            return redirect()->route($request->input('route'))->with('success', 'La empresa ha sido actualizada con exito');
        }else{
            return redirect()->route($request->input('route'))->with('error', 'No se ha modificado ningun dato en el formulario, para hacer una actualización modifique el contenido');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $delete = DB::table('empresa')->where('id',$id)->update([
            'logica_delete' => 0
        ]);

        if ($delete){
            return response()->json(['success'=>true,'message'=>'Se elimino correctamente']);
        }else{
            return response()->json(['success'=>false,'message'=>'Error, intente mas tarde']);
        }
    }

    function asignar($id_empresa){

        $medicos = DB::table('medico_empresa')->join('users','users.id','=','medico_empresa.id_medico')->
        where('id_empresa',$id_empresa)->where('medico_empresa.logica_delete',1)->select('medico_empresa.id','users.name','users.last_name')->get();

        $c = 1;
        $tabla = '';
        foreach ($medicos as $medico){
            $tabla.= '<tr>';
            $tabla.= '<td>'.$c++.'</td>';
            $tabla.= '<td>'.$medico->name.' '.$medico->last_name.'</td>';
            $tabla.= '<td> <buton class="btn btn-danger" onclick="deleteMedico('.$medico->id.','.$id_empresa.')"> <i class="fas fa-trash"></i> </buton> </td>';
            $tabla.= '</tr>';
        }

        return response()->json(['tabla'=>$tabla]);

    }

    function asignar_guardar(Request $request){

        $verific = DB::table('medico_empresa')->where('id_medico',$request->input('medico_selec'))
        ->where('id_empresa',$request->input('id_empresa'))->where('logica_delete',1)->count();

        if ($verific == 0){
            $medico_trabajo = new MedicoEmpresa();
            $medico_trabajo->id_medico = $request->input('medico_selec');
            $medico_trabajo->id_empresa = $request->input('id_empresa');
            $medico_trabajo->save();

            $medicos = DB::table('medico_empresa')->join('users','users.id','=','medico_empresa.id_medico')->
            where('id_empresa',$request->input('id_empresa'))->where('medico_empresa.logica_delete',1)->select('medico_empresa.id','users.name','users.last_name')->get();

            $c = 1;
            $tabla = '';
            foreach ($medicos as $medico){
                $tabla.= '<tr>';
                $tabla.= '<td>'.$c++.'</td>';
                $tabla.= '<td>'.$medico->name.' '.$medico->last_name.'</td>';
                $tabla.= '<td> <buton class="btn btn-danger" onclick="deleteMedico('.$medico->id.','.$request->input('id_empresa').')"> <i class="fas fa-trash"></i> </buton> </td>';
                $tabla.= '</tr>';
            }

            return response()->json(['tabla'=>$tabla,'success'=>true,'message'=>'Excelente, Se guardo de manera exitosa']);
        }else{
            return response()->json(['success'=>false,'message'=>'Error, el medico ya se encuentra asignado']);
        }



    }

    function asignar_delete($id_medico,$id_empresa){
        $delete = DB::table('medico_empresa')->where('id',$id_medico)->update([
            'logica_delete' => 0,
        ]);

        $medicos = DB::table('medico_empresa')->join('users','users.id','=','medico_empresa.id_medico')->
        where('id_empresa',$id_empresa)->where('medico_empresa.logica_delete',1)->select('medico_empresa.id','users.name','users.last_name')->get();

        $c = 1;
        $tabla = '';
        foreach ($medicos as $medico){
            $tabla.= '<tr>';
            $tabla.= '<td>'.$c++.'</td>';
            $tabla.= '<td>'.$medico->name.' '.$medico->last_name.'</td>';
            $tabla.= '<td> <buton class="btn btn-danger" onclick="deleteMedico('.$medico->id.')"> <i class="fas fa-trash"></i> </buton> </td>';
            $tabla.= '</tr>';
        }

        return response()->json(['tabla'=>$tabla,'success'=>true,'message'=>'Excelente, Se elimino de manera exitosa']);
    }

    function empresa_perfil(){

        $dato_user = DB::table('datos_colaborador')->where('id_user',auth()->user()->id)->first();

        $rugros = Rugro::where('logica_delete',1)->get();

resources/views/admin/empresa/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">

                <div class="row mb-4">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Lista de usuario</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Empresa</a></li>
                            <li class="breadcrumb-item active">Lista de usuario</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->


                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif


                @if (session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif

                <div class="row mb-4">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Importar usuarios</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Tabla de usuarios</h3>
                            </div>
                            <div class="card-body">
                                <table class="table" id="example2">
                                    <thead>
                                    <th>Nº</th>
                                    <th>Nombre</th>
                                    <th>Apellido</th>
                                    <th>Documento</th>
                                    <th>Tipo Usuario</th>
                                    <th>Opinion</th>
                                    </thead>
                                    <tbody>
                                    @php $c = 1; @endphp
                                    @foreach($usuarios as $usuario)
                                        <tr>
                                            <td>{{$c++}}</td>
                                            <td>{{$usuario->name}}</td>
                                            <td>{{$usuario->last_name}}</td>
                                            <td>{{$usuario->documento}}</td>
                                            <td>{{$usuario->title}}</td>
                                            <td>
                                                <a href="{{route('user.edit',$usuario->id)}}" class="btn btn-success"><i class="fas fa-pen"></i></a>
                                                <button onclick="deleteUsuario({{$usuario->id}},'{{$usuario->name}} {{$usuario->last_name}}')" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <form action="{{route('import.user')}}" enctype="multipart/form-data" method="post">
                @csrf
                <input type="hidden" id="id_empresa" value="{{$id}}" name="id_empresa">
                <input type="hidden" id="route" value="empresa.show" name="route">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Importar Personal</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <a href="{{asset('orden-importacion.xlsx')}}" type="button" download>Descargar orden de importacion</a>
                        </div>
                        <div class="form-group">
                            <p><strong>Observaciones</strong> <br> El la columna tipo_usuario colocar: <br> 1 si es el administrador de la empresa
                                <br> 2 si son los colaboradores</p>
                        </div>
                        <div class="form-group">
                            <input type="file" name="personimport" accept=".xlsx,.xls">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Salir</button>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
            </form>
        </div>
    </div>
    </div>
@endsection

@section('script')
    <script>

        $("#example2").DataTable({
            "responsive": true,
            "autoWidth": false,
            dom: 'Bfrtip',
            buttons: [
                'excel'
            ]
        });

        function deleteUsuario(id,name) {
            swal({
                title: `¿ Estas seguro que quieres eliminar a ${name} ?`,
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajaxSetup({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            }
                        });

                        $.ajax({
                            url: '../../user/'+id,
                            type: 'delete',
                            dataType: "JSON",
                            data: {
                                "id": id
                            },
                            success: function (response)
                            {
                                if(response.success){
                                    swal(response.message, {
                                        icon: "success",
                                    });
                                    setTimeout(function () {
                                        location.reload();
                                    },1000)
                                }
                            },
                        })


                    }
                });
        }
    </script>
@endsection